# Generated by Django 4.1.2 on 2022-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
                ('user_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=6)),
            ],
        ),
    ]
