# Generated by Django 4.1 on 2022-11-07 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_icon",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_phone",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_gender",
            field=models.CharField(default="male", max_length=6),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("de72fc27-5e4c-11ed-8ac0-e0d464c9992d"),
                max_length=250,
            ),
        ),
    ]
