# Generated by Django 4.1 on 2022-11-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_postcode",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
