# Generated by Django 4.1.2 on 2022-10-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userprofile_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfileTest',
        ),
    ]
