# Generated by Django 4.1 on 2022-11-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_userprofile_user_postcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_id",
            new_name="id",
        ),
    ]
