# Generated by Django 4.1 on 2022-11-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_rename_user_id_userprofile_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="id",
            new_name="user_id",
        ),
    ]
