# Generated by Django 4.1.2 on 2022-10-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_userprofile_userprofiletest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileTest',
            new_name='UserProfile',
        ),
    ]
