# Generated by Django 4.1.2 on 2022-10-30 21:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_userprofiletest_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(default=uuid.UUID('4c89ea04-5898-11ed-90e1-e0d464c9992d'), max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
