# Generated by Django 4.1.2 on 2022-10-30 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userprofile_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(default=uuid.UUID('c0becb3e-5899-11ed-ba45-e0d464c9992d'), max_length=250),
        ),
    ]
