# Generated by Django 4.1 on 2022-11-01 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_alter_userprofile_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("ba675bea-5987-11ed-8f2f-e0d464c9992d"),
                max_length=250,
            ),
        ),
    ]
