# Generated by Django 4.1 on 2022-11-01 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_alter_userprofile_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": False},
        ),
    ]
