# Generated by Django 4.1 on 2022-11-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0009_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="login_userprofile",
        ),
    ]
