# Generated by Django 4.1 on 2022-11-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_name",
            field=models.CharField(
                blank=True, default="free", max_length=250, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_price",
            field=models.CharField(blank=True, default="0", max_length=250),
        ),
    ]
