# Generated by Django 4.1 on 2022-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0002_alter_plan_plan_name_alter_plan_plan_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="plan_description",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_image",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
