# Generated by Django 4.1 on 2022-11-09 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.CharField(blank=True, default="0", max_length=250)),
                (
                    "federal_skilled_worker",
                    models.CharField(default="0", max_length=250),
                ),
                (
                    "quebec_skilled_worker",
                    models.CharField(default="0", max_length=250),
                ),
                (
                    "provincial_nominee_program",
                    models.CharField(default="0", max_length=250),
                ),
                ("family_sponsorship", models.CharField(default="0", max_length=250)),
                ("business_immigrant", models.CharField(default="0", max_length=250)),
                (
                    "canadian_experience_class",
                    models.CharField(default="0", max_length=250),
                ),
                ("total", models.CharField(default="0", max_length=250)),
            ],
            options={
                "db_table": "category_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CountryData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=250)),
                ("total", models.CharField(blank=True, default="0", max_length=250)),
            ],
            options={
                "db_table": "country_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DestinationData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("province", models.CharField(blank=True, default="", max_length=250)),
                (
                    "federal_skilled_worker",
                    models.CharField(blank=True, default="0", max_length=250),
                ),
                (
                    "quebec_skilled_worker",
                    models.CharField(default="0", max_length=250),
                ),
                (
                    "provincial_nominee_program",
                    models.CharField(default="0", max_length=250),
                ),
                ("family_sponsorship", models.CharField(default="0", max_length=250)),
                ("business_immigrant", models.CharField(default="0", max_length=250)),
                (
                    "canadian_experience_class",
                    models.CharField(default="0", max_length=250),
                ),
            ],
            options={
                "db_table": "destination_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ImmigrationStatusData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.CharField(blank=True, default="", max_length=250)),
                (
                    "gender",
                    models.CharField(blank=True, default="male", max_length=250),
                ),
                ("age", models.CharField(blank=True, default="0", max_length=250)),
                (
                    "category",
                    models.CharField(
                        blank=True, default="Canadian Experience Class", max_length=250
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, default="India", max_length=250),
                ),
                ("address", models.CharField(blank=True, default="ON", max_length=250)),
                (
                    "status",
                    models.CharField(blank=True, default="In Progress", max_length=250),
                ),
            ],
            options={
                "db_table": "immigration_data",
                "managed": True,
            },
        ),
    ]
