# Generated by Django 4.1 on 2022-11-27 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datasource", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydata",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=250,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="countrydata",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=250,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="destinationdata",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=250,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="immigrationstatusdata",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=250,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
